
language: python
python:
  - "2.7"
  - "3.4"
cache: pip
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"
# command to install dependencies
before_install:
  - cd web
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script: python apps/manage.py test
